name: lint
on: [ push, pull_request ]

jobs:
  Lint-Policies:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - run: go install github.com/hashicorp/hcl/v2/cmd/hclfmt@latest
      - name: Lint-Policies
        run: find . -name "*.hcl"  -print0 | xargs -0 $(go env GOPATH)/bin/hclfmt --require-no-change

  Lint-sql-queries:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: Install SQLFluff
        run: "pip install sqlfluff"
      - name: Lint queries
        run: "sqlfluff lint ./queries"
      - name: Fail if queries are changed
        run: |
          test "$(git status -s ./queries | wc -l)" -eq 0
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_CHANNEL: oss-tests
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'GCP Policies - queries lint failed'
          SLACK_TITLE: GCP Policies - queries lint failed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}